import { useAutoAnimate } from "@formkit/auto-animate/react";
import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import React, { useState } from "react";
import Login from "~/components/Login";
import Register from "~/components/Register";
import { getServerAuthSession } from "~/server/auth";

export default function Auth() {
  const [currentCard, setCurrentCard] = useState<"Login" | "Register">("Login");
  const [parent] = useAutoAnimate();

  return (
    <>
      <Head>
        <title>Kanban task management</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className="mx-3 flex h-screen items-center justify-center sm:mx-0"
        ref={parent}
      >
        {currentCard === "Login" ? (
          <Login setCurrentCard={setCurrentCard} />
        ) : (
          <Register setCurrentCard={setCurrentCard} />
        )}
      </main>
    </>
  );
}

Auth.isLayout = false;
