import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Board from "~/components/Board";
import Sidebar from "~/components/Sidebar";
import { api } from "~/lib/api";
import { Eye } from "lucide-react";
import { useAutoAnimate } from "@formkit/auto-animate/react";
import { useSidebar } from "~/lib/hooks/use-sidebar";
import TaskCard from "~/components/TaskCard";
import EditTask from "~/components/EditTask";

export default function Home() {
  const [parent] = useAutoAnimate();
  const [showSidebar, openSidebar] = useSidebar((state) => [
    state.isOpen,
    state.onOpen,
  ]);

  return (
    <>
      <Head>
        <title>Kanban task management</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative flex h-screen">
        <section ref={parent}>
          {showSidebar ? (
            <Sidebar />
          ) : (
            <button
              onClick={openSidebar}
              className={`absolute bottom-10 left-0 w-14 rounded-r-full bg-main-color py-3 pl-5 text-white transition-all duration-300 dark:bg-main-background dark:hover:bg-main-color`}
            >
              <Eye className="h-[1.2rem] w-[1.2rem]" />
            </button>
          )}
        </section>
        <Board />
        <TaskCard />
        <EditTask />
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
