import { useAutoAnimate } from "@formkit/auto-animate/react";
import { Eye } from "lucide-react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import LoadingBar from "react-top-loading-bar";
import Sidebar from "~/components/Sidebar";
import { useSidebar } from "~/lib/hooks/use-sidebar";
import CreateBoard from "./CreateBoard";
import Plans from "./Plans";
import { ScrollArea } from "./ui/scroll-area";

interface Props {
  children: JSX.Element;
}

export default function Layout({ children }: Props) {
  const [parent] = useAutoAnimate();
  const [showSidebar, openSidebar] = useSidebar((state) => [
    state.isOpen,
    state.onOpen,
  ]);
  const [progress, setProgress] = useState(0);
  const router = useRouter();

  useEffect(() => {
    const handleRouteChangeComplete = () => {
      setProgress(100);
    };

    const handleRouteChangeStart = () => {
      setProgress(40);
    };

    router.events.on("routeChangeComplete", handleRouteChangeComplete);
    router.events.on("routeChangeStart", handleRouteChangeStart);

    // If the component is unmounted, unsubscribe
    // from the event with the `off` method:
    return () => {
      router.events.off("routeChangeComplete", handleRouteChangeComplete);
      router.events.off("routeChangeStart", handleRouteChangeStart);
    };
  }, [router, setProgress]);

  return (
    <>
      <Head>
        <title>Kanban task management</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoadingBar
        color="#635FC7"
        progress={progress}
        waitingTime={400}
        onLoaderFinished={() => setProgress(0)}
      />

      <main className="relative flex h-screen">
        <section ref={parent}>
          {showSidebar ? (
            <ScrollArea className="hidden h-full w-64 border-0 border-r border-solid border-main-border bg-main-background lg:flex">
              <Sidebar />
            </ScrollArea>
          ) : (
            <button
              onClick={openSidebar}
              className={`absolute bottom-10 left-0 z-20 hidden w-14 rounded-r-full bg-main-color py-3 pl-5 text-white transition-all duration-300 dark:bg-main-background dark:hover:bg-main-color lg:flex`}
            >
              <Eye className="h-[1.2rem] w-[1.2rem]" />
            </button>
          )}
        </section>
        {children}

        <CreateBoard />
        <Plans />
      </main>
    </>
  );
}
